<template>
  <div class="mt-2.5 mx-10 mb-10">
    <div class="grid grid-cols-1 md:grid-cols-3 sm:grid-cols-1 gap-5">
      <div
        class="w-full aspect-video relative cursor-pointer"
        v-for="video in displayedVideos.slice(0, max)"
        :key="video.id"
        @click="handleVideoClick(video.id)"
      >
        <iframe
          :src="getVideoUrl(video.id)"
          class="absolute inset-0 w-full h-full"
          frameborder="0"
          title="YouTube video player"
          loading="lazy"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <!-- overlay removed so iframe is interactive -->
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    // Optional: if provided, component will use this array
    videos: {
      type: Array,
      required: false,
      default: () => []
    },
    // Optional: channel id to fetch in real-time from server endpoint
    channelId: {
      type: String,
      required: false,
      default: null
    },
    // number of tiles to show (default 3)
    max: {
      type: Number,
      required: false,
      default: 6
    }
  },
  data() {
    return {
      fetchedVideos: []
    };
  },
  computed: {
    displayedVideos() {
      // Prefer fetched static JSON (from CI) or runtime fetch; fall back to provided prop
      if (this.fetchedVideos && this.fetchedVideos.length) return this.fetchedVideos;
      return (this.videos && this.videos.length) ? this.videos : [];
    }
  },
  methods: {
    getVideoUrl(videoId) {
      return `https://www.youtube.com/embed/${videoId}`;
    },
    handleVideoClick(videoId) {
      this.$emit('video-clicked', videoId);
    },
    async fetchVideos() {
      // Runtime server endpoint fallback (useful in dev or if you deploy a server elsewhere)
      if (!this.channelId) return;
      try {
        const res = await fetch(`/api/youtube?channelId=${encodeURIComponent(this.channelId)}&max=${this.max}`);
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const json = await res.json();
        this.fetchedVideos = json.map(v => ({ id: v.videoId || v.id, ...v }));
      } catch (err) {
        // silently fail — keep empty fetchedVideos
      }
    },

    async fetchStaticJson() {
      // Try to load the generated static JSON created by the GitHub Action
      try {
        const res = await fetch('/latest-videos.json', { cache: 'no-cache' });
        if (!res.ok) return;
        const json = await res.json();
        if (Array.isArray(json) && json.length) {
          this.fetchedVideos = json.map(v => ({ id: v.videoId || v.id, ...v }));
        }
      } catch (err) {
        // ignore errors and allow other fallbacks
      }
    }
  },
  mounted() {
    // 1) Prefer static JSON generated by CI (GitHub Actions)
    // 2) Fallback to server endpoint if channelId is provided (useful for dev)
    // 3) Finally fall back to videos prop
    if ((!this.videos || !this.videos.length)) {
      this.fetchStaticJson().then(() => {
        if ((!this.fetchedVideos || !this.fetchedVideos.length) && this.channelId) {
          this.fetchVideos();
        }
      });
    }
  }
};
</script>
